[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.85"
cpal = "0.15.3"
hound = "3.5.1"
tokio = { version = "1.43.0", features = [
    "fs",
    "io-util",
    "rt-multi-thread",
    "macros",
    "time",
    "sync",
] }
thiserror = "2.0.11"
