[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.86"
bytes = "1.10.0"
config = "0.15.8"
cpal = "0.15.3"
directories = "6.0.0"
hound = "3.5.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
thiserror = "2.0.11"
tokio = { version = "1.43.0", features = [
    "fs",
    "io-util",
    "macros",
    "rt-multi-thread",
    "sync",
    "net",
    "time",
] }
tokio-stream = "0.1.17"
reqwest = { version = "0.12.12", features = ["json", "stream"] }
url = "2.5.4"
whisper-rs = "0.13.2"
