[geocoding]
base_url = "https://nominatim.openstreetmap.org/search"
user_agent = "eagely's Voice Assistant/1.0"

[llm]
base_url = "http://localhost:11434"
model = "deepseek-r1:7b"

[rasa]
base_url = "http://localhost:5005"

[recorder]
device_name = "pipewire"

[response]
response_type = "text"

[server]
host = "127.0.0.1"
port = 8080

[transcriber]
model_path = "base.bin"
use_gpu = true

[tts]
base_url = "http://localhost:5000"
voice = "en_US/ljspeech"

[user]
default_location = "Vienna"

[weather]
base_url = "https://api.openweathermap.org/data/3.0/onecall"
