[geocoding]
base_url = "https://nominatim.openstreetmap.org/search/"
user_agent = "eagely's Voice Assistant/1.0"
implementation = "nominatim"

[llm]
deepseek_base_url = "https://api.deepseek.com/"
ollama_base_url = "http://localhost:11434/"
deepseek_model = "deepseek-chat"
ollama_model = "deepseek-r1:7b"
implementation = "ollama"

[parsing]
rasa_base_url = "http://localhost:5005/"
implementation = "patternmatch"

[recording]
device_name = "pipewire"
implementation = "local"
remote_url = "ws://localhost:5555/"

[response]
response_kind = "audio"

[server]
host = "127.0.0.1"
port = 8080

[transcription]
local_model_path = "base.bin"
local_use_gpu = true
deepgram_base_url = "https://api.deepgram.com/v1/"
implementation = "deepgram"

[synthesis]
elevenlabs_base_url = "https://api.elevenlabs.io/"
elevenlabs_model_id = "eleven_multilingual_v2"
elevenlabs_voice_id = "Xb7hH8MSUJpSbSDYk0k2"
piper_base_url = "http://localhost:5000/"
piper_voice = "en_US-ljspeech-high.onnx"
implementation = "elevenlabs"

[weather]
base_url = "https://api.openweathermap.org/data/3.0/onecall/"
implementation = "openweathermap"
